add doc for arctern_spark and try to be consistent with pandas arctern
zilliztech/arctern pull request #871
Opened 2020-07-15 11:36 UTC by shengjh

Please help to review the doc.

2020-07-15 11:44 UTC, Emma-Song requested changes

2020-07-15 11:44 UTC, Emma-Song commented on spark/arctern_spark/geodataframe.py
> +        Dissolves geometries within `by` into a single observation.
use double quotes as code format, for example \`\`by\`\`

2020-07-15 11:44 UTC, Emma-Song commented on spark/arctern_spark/geodataframe.py
> +        Observations associated with each `by` group will be aggregated using the `aggfunc`.
\`\`by\`\` and \`\`aggfunc\`\`

2020-07-15 11:44 UTC, Emma-Song commented on spark/arctern_spark/geodataframe.py
> +            Aggregation function for manipulation of data associated with each group, by default "first". Passed to pandas `groupby.agg` method.
\`\`groupby.agg\`\`

2020-07-16 02:54 UTC, Emma-Song approved these changes

2020-07-16 03:25 UTC, shengjh commented
Additionally, `GeoDataFrame::init `, `sjoin`, `GeoDataFrame::merge` doc have been updated. Please leave a review. Thanks

2020-07-16 03:47 UTC, Emma-Song requested changes

2020-07-16 03:47 UTC, Emma-Song commented on spark/arctern_spark/geodataframe.py
> +        A GeoDataFrame object is a pandas.DataFrame that has columns with geometry.
A GeoDataFrame object is a pandas.DataFrame that has columns with **geometries.**

2020-07-16 03:47 UTC, Emma-Song commented on spark/arctern_spark/geodataframe.py
> +            Dict can contain Series, GeoSeries, arrays, constants, or list-like objects
add a full stop `.` at the end

2020-07-16 03:47 UTC, Emma-Song commented on spark/arctern_spark/geodataframe.py
> +            Note that if `data` is a pandas DataFrame, a Spark DataFrame, a Koalas Series, and a GeoSeries,
use double quote for code format

2020-07-16 03:47 UTC, Emma-Song commented on spark/arctern_spark/geodataframe.py
> +            Data type to force. Only a single dtype is allowed. If None, infer.
If None, infers the data type based on the data.

2020-07-16 03:47 UTC, Emma-Song commented on spark/arctern_spark/geodataframe.py
> +            Copy data from inputs. Only affects DataFrame / 2d ndarray input.
Copys
DataFrame **or** 2d ndarray input

2020-07-16 03:47 UTC, Emma-Song commented on spark/arctern_spark/geodataframe.py
> +            if crs is a string, will set all ``geometries`` columns' crs to param ``crs``.
if > If
crs > \`\`crs\`\`
will set > sets

2020-07-16 03:47 UTC, Emma-Song commented on spark/arctern_spark/geodataframe.py
> +        Set an existing column in the GeoDataFrame to a geometry column, which is used to perform geometric calculations later.
Sets

2020-07-16 03:47 UTC, Emma-Song commented on spark/arctern_spark/geodataframe.py
> +        Setting an column to a geometry column will attemp to construct geometry for each row of this column,
This function attempts to construct geometries for each row of the given column, so all data in \`\`col\`\` should be in WKT or WKB format.

2020-07-16 03:47 UTC, Emma-Song commented on spark/arctern_spark/geodataframe.py
> +        Merge GeoDataFrame objects with a database-style join.
Merges

2020-07-16 03:47 UTC, Emma-Song commented on spark/arctern_spark/geodataframe.py
> +                e.g. if `left` with indices (a, x) and `right` with indices (b, x), the result will
code format

2020-07-16 03:47 UTC, Emma-Song commented on spark/arctern_spark/geodataframe.py
> +        on: Column or index level names to join on. These must be found in both GeoDataFrames. If on
If \`\`on\`\` is None

2020-07-16 03:47 UTC, Emma-Song commented on spark/arctern_spark/geodataframe.py
> +        left_index: Use the index from the left GeoDataFrame as the join key(s). If it is a
Uses

2020-07-16 03:47 UTC, Emma-Song commented on spark/arctern_spark/geodataframe.py
> +        right_index: Use the index from the right GeoDataFrame as the join key. Same caveats as
Uses

2020-07-16 03:47 UTC, Emma-Song commented on spark/arctern_spark/geodataframe.py
> +            Return a merged GeoDataFrame.
Returns

2020-07-16 03:47 UTC, Emma-Song commented on spark/arctern_spark/geodataframe.py
> +        Construct a GeoDataFrame from a file or url.
The subject is "the function", so should add a 's' to all verbs. Please change the words below.

2020-07-16 03:47 UTC, Emma-Song commented on spark/arctern_spark/sjoin.py
> +        * *left:* use keys from left_df
Uses

2020-07-16 04:28 UTC, shengjh commented
All problems have been solved(i hope), please review again @Emma-Song

2020-07-16 06:58 UTC, Emma-Song approved these changes

2020-07-16 06:58 UTC, merged